import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
<<<<<<< HEAD
import { Footer } from "@/components/Footer";
=======
import { Toaster } from "@/components/ui/toaster";
>>>>>>> 2d351426b10a22da71791d9f7756a001918914b4

const sen = Sen({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sen.className}>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
