name: Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-next:
    name: Build Next
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build-storybook

  integration-chrome:
    name: Playwright Integration Tests (Chrome)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

      - name: Run Playwright Tests
        run: pnpm test:integration --browser=chromium

  integration-firefox:
    name: Playwright Integration Tests (Firefox)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

      - name: Run Playwright Tests
        run: pnpm test:integration --browser=firefox

  integration-webkit:
    name: Playwright Integration Tests (Webkit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

      - name: Run Playwright Tests
        run: pnpm test:integration --browser=webkit

  e2e-chrome:
    name: Playwright E2E Tests (Chrome)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

      - name: Run Playwright Tests
        run: pnpm test:e2e --browser=chromium

  e2e-firefox:
    name: Playwright E2E Tests (Firefox)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

      - name: Run Playwright Tests
        run: pnpm test:e2e --browser=firefox

  e2e-webkit:
    name: Playwright E2E Tests (Webkit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run build
        run: pnpm build
        env:
          SERVICE_ENV: test

      - name: Run Playwright Tests
        run: pnpm test:e2e --browser=webkit
